Updated the GitHub workflows and/or the README file to the latest versions.

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -3,8 +3,29 @@
 # For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
 # https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
 
-# TODO:
-# * Sort out the builders for the PDF manuals and vignettes (since a tex installation may be needed for those), perhaps depending on the OS.
+# Each entry in the config matrix must have the following keys:
+#
+# os: windows-latest, macOS-latest, ubuntu-20.04, etc. (as of this writing)
+#
+# r: devel or release
+#
+# rspm: Linux only, just leave it alone.
+#
+# timeout: in minutes
+#
+# flags: a comma (or some other aesthetically pleasing and
+#   non-forbidden symbol) separated list of flags. Currently
+#   supported:
+#
+#   binaries: build and upload as an artefact a binary version (particularly for MacOS and Windows).
+#
+#   full: run with ENABLE_statnet_TESTS.
+#
+#   vignettes: build vignettes and manuals; otherwise ignore.
+#
+#   ubsan: compile with -fsanitize=undefined and fail on any errors identified.
+#
+#   covr: run in covr mode may be used with 'full' but probably not with others.
 
 on: [push, pull_request]
 
@@ -64,13 +85,24 @@ jobs:
         run: |
           if [[ "${{ env.IAM }}" == 'public' ]] # Public: full set.
           then
-            echo "::set-output name=matrix::{\"config\":[{\"os\":\"windows-latest\", \"r\":\"release\", \"timeout\":360, \"full\":\"no\", \"covr\":\"no\"}, {\"os\":\"macOS-latest\", \"r\":\"release\", \"timeout\":360, \"full\":\"no\", \"covr\":\"no\"}, {\"os\":\"ubuntu-20.04\", \"r\":\"release\", \"rspm\":\"https://packagemanager.rstudio.com/cran/__linux__/focal/latest\", \"timeout\":360, \"full\":\"yes\", \"covr\":\"no\"}, {\"os\":\"ubuntu-20.04\", \"r\":\"devel\", \"rspm\":\"https://packagemanager.rstudio.com/cran/__linux__/focal/latest\", \"timeout\":360, \"full\":\"no\", \"covr\":\"no\"}, {\"os\":\"ubuntu-20.04\", \"r\":\"release\", \"rspm\":\"https://packagemanager.rstudio.com/cran/__linux__/focal/latest\", \"timeout\":360, \"full\":\"yes\", \"covr\":\"yes\"}]}"
+            config='{"config":[
+            {"os":"windows-latest", "r":"release", "timeout":360, "flags":"binaries"},
+            {"os":"macOS-latest", "r":"release", "timeout":360, "flags":"binaries"},
+            {"os":"ubuntu-20.04", "r":"release", "rspm":"https://packagemanager.rstudio.com/cran/__linux__/focal/latest", "timeout":360, "flags":"full, ubsan"},
+            {"os":"ubuntu-20.04", "r":"devel", "rspm":"https://packagemanager.rstudio.com/cran/__linux__/focal/latest", "timeout":360, "flags":"vignettes"},
+            {"os":"ubuntu-20.04", "r":"release", "rspm":"https://packagemanager.rstudio.com/cran/__linux__/focal/latest", "timeout":360, "flags":"full, covr"}]}'
           elif [[ "${{ env.FOUND_PUBLIC }}" != '0' ]] # Private with no public analogue: reduced set.
           then
-            echo "::set-output name=matrix::{\"config\":[{\"os\":\"ubuntu-20.04\", \"r\":\"release\", \"rspm\":\"https://packagemanager.rstudio.com/cran/__linux__/focal/latest\", \"timeout\":10, \"full\":\"no\", \"covr\":\"no\"}]}"
-          else
-            echo "::set-output name=matrix::" # Private with public analogue: no checking.
+            config='{"config":[
+            {"os":"ubuntu-20.04", "r":"release", "rspm":"https://packagemanager.rstudio.com/cran/__linux__/focal/latest", "timeout":10, "flags":"none"}
+            ]}'
+          else # Private with public analogue: no checking.
+            config=''
           fi
+          config="${config//'%'/'%25'}"
+          config="${config//$'\n'/'%0A'}"
+          config="${config//$'\r'/'%0D'}"
+          echo "::set-output name=matrix::$config"
 
   R-CMD-check:
     needs: Set-Matrix-Private
@@ -79,7 +111,7 @@ jobs:
 
     runs-on: ${{ matrix.config.os }}
 
-    name: ${{ matrix.config.os }} (${{ matrix.config.r }}, statnet tests ${{ matrix.config.full }}, covr ${{ matrix.config.covr }})
+    name: ${{ matrix.config.os }} (r ${{ matrix.config.r }}, flags ${{ matrix.config.flags }})
 
     strategy:
       fail-fast: false
@@ -107,7 +139,17 @@ jobs:
         with:
           r-version: ${{ matrix.config.r }}
 
+      - name: Install GhostScript (on Linux if running vignettes)
+        if: runner.os == 'Linux' && contains(matrix.config.flags, 'vignettes')
+        run: |
+          /usr/bin/sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ghostscript
+        shell: bash
+
       - uses: r-lib/actions/setup-pandoc@v1
+
+      - name: Install tinytex (system)
+        if: contains(matrix.config.flags, 'vignettes')
+        uses: r-lib/actions/setup-tinytex@v1
 
       - name: Query dependencies
         run: |
@@ -140,48 +182,89 @@ jobs:
           remotes::install_cran("covr")
         shell: Rscript {0}
 
+      - name: Install tinytex (R)
+        if: contains(matrix.config.flags, 'vignettes')
+        run: |
+          remotes::install_cran("tinytex")
+          tinytex:::install_yihui_pkgs()
+        shell: Rscript {0}
+
       - name: Build
-        if: matrix.config.covr == 'no' && runner.os != 'Linux'
+        if: contains(matrix.config.flags, 'binaries')
         run: |
           dir.create("binaries", FALSE)
           pkgbuild::build(binary=TRUE, vignettes=FALSE, dest_path = "binaries")
         shell: Rscript {0}
 
       - name: Upload build results
-        if: matrix.config.covr == 'no' && runner.os != 'Linux' && !failure()
-        uses: actions/upload-artifact@main
+        if: contains(matrix.config.flags, 'binaries') && !failure()
+        uses: actions/upload-artifact@v2
         with:
           name: ${{ runner.os }}-r${{ matrix.config.r }}-binaries
           path: binaries
 
       - name: Clean up build results
-        if: matrix.config.covr == 'no' && runner.os != 'Linux'
+        if: contains(matrix.config.flags, 'binaries')
         run: rm -rf binaries
         shell: bash
 
       - name: Check
-        if: matrix.config.covr == 'no'
+        if: contains(matrix.config.flags, 'covr') == false
         timeout-minutes: ${{ matrix.config.timeout }}
         env:
           _R_CHECK_CRAN_INCOMING_REMOTE_: false
-          _R_CHECK_FORCE_SUGGESTS_: ${{ runner.os != 'macOS' }} # Rmpi is not available on macOS.
-          ENABLE_statnet_TESTS: ${{ matrix.config.full }}
-        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran", "--no-build-vignettes"), build_args = c("--no-manual", "--no-build-vignettes"), error_on = "error", check_dir = "check")
+          _R_CHECK_FORCE_SUGGESTS_: false
+          ENABLE_statnet_TESTS: ${{ contains(matrix.config.flags, 'full') }}
+          R_VIGNETTES: ${{ contains(matrix.config.flags, 'vignettes') }}
+          FAIL_ON_WARN: ${{ contains(matrix.config.flags, 'strict') }}
+          USE_UBSAN: ${{ contains(matrix.config.flags, 'ubsan') }}
+        run: |
+          if(Sys.getenv("R_VIGNETTES") == "true"){
+            check_args <- c("--as-cran")
+            build_args <- c("--compact-vignettes=gs+qpdf")
+          }else{
+            check_args <- c("--no-manual", "--as-cran", "--ignore-vignettes")
+            build_args <- c("--no-manual", "--no-build-vignettes")
+          }
+
+          error_on <- if(Sys.getenv("FAIL_ON_WARN") == "true") "warning" else "error"
+
+          if(Sys.getenv("USE_UBSAN") == "true"){
+            Sys.setenv(PKG_LIBS="-fsanitize=undefined",
+                       PKG_CFLAGS="-fsanitize=undefined",
+                       UBSAN_OPTIONS="print_stacktrace=1")
+          }
+
+          rcmdcheck::rcmdcheck(args = check_args, build_args = build_args, error_on = error_on, check_dir = "check")
         shell: Rscript {0}
 
+      - name: Check UBSAN output
+        if: contains(matrix.config.flags, 'ubsan')
+        run: |
+          find check/ -name '*.Rout' -print0 | xargs -0 grep -E '\.[hc]:[0-9]+:[0-9]+: +runtime error:' > check/ubsan.err
+          if [ -s check/ubsan.err ]
+          then
+            echo "UBSAN errors:" >&2
+            cat check/ubsan.err >&2
+            exit 1
+          fi
+        shell: bash
+        
       - name: Upload check results
-        if: matrix.config.covr == 'no' && failure()
-        uses: actions/upload-artifact@main
+        if: contains(matrix.config.flags, 'covr') == false && failure()
+        uses: actions/upload-artifact@v2
         with:
           name: ${{ runner.os }}-r${{ matrix.config.r }}-results
-          path: check
+          path: |
+            check
+            !check/*/00_pkg_src
 
       - name: Test coverage
-        if: matrix.config.covr == 'yes'
+        if: contains(matrix.config.flags, 'covr')
         timeout-minutes: ${{ matrix.config.timeout }}
         env:
           _R_CHECK_CRAN_INCOMING_REMOTE_: false
           _R_CHECK_FORCE_SUGGESTS_: ${{ runner.os != 'macOS' }} # Rmpi is not available on macOS.
-          ENABLE_statnet_TESTS: ${{ matrix.config.full }}
+          ENABLE_statnet_TESTS: ${{ contains(matrix.config.flags, 'full') }}
         run: covr::codecov(type=c("tests","examples"))
         shell: Rscript {0}
